# Note: In a yml each level is padded by 2 spaces
name: Flutter

on:
  # Runs this action when you push on main
  push:
    branches: [ "main" ]
  # Runs this when a PR against main is created
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_job:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest
    permissions: # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests

    steps:

      # Clones the project on the machine
      - uses: actions/checkout@v4

      # Installs flutter and related dependency on this machine
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.3'

      # Fetches all dependencies from pub
      - name: Install dependencies
        run: |
          flutter pub get
          cd packages/api_service
          flutter pub get
          cd ../authentication_repository
          flutter pub get
          cd ../cache
          flutter pub get
          cd ../..

      # Format the code
      - name: Format Dart code
        run: dart format .

      # Commit and push any changes if formatting was required
      - name: Commit file
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit -a -m "Auto-format code by GitHub Actions" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      
      # Checks for Semantic errors. Can be configured using analysis_options.yaml
      - name: Analyze project source
        run: flutter analyze
        # optionally use --fatal-warnings to stop execution if any warnings are found

      # Runs unit test
      - name: Run tests
        run: |
          flutter test || echo "No tests found"
